import PDFDocument from "pdfkit";
import fs from "fs";

function money(n: any) {
  const v = Number(n ?? 0);
  return `Rs. ${Number.isFinite(v) ? v : 0}`;
}

function safeText(v: any) {
  return String(v ?? "-");
}

function fmtDate(v: any) {
  try {
    return v ? new Date(v).toLocaleString() : "-";
  } catch {
    return "-";
  }
}

export async function generateInvoicePdfBuffer(params: {
  order: any; // order lean/object is ok
  company: { name: string; address: string };
  logoPath?: string; // optional local file path
  user?: any; // optional - backward compatible
  customer?: { name?: string; email?: string; phone?: string };
}) {
  const { order, company, logoPath, user } = params;

  const doc = new PDFDocument({ size: "A4", margin: 40 });
  const chunks: Buffer[] = [];

  doc.on("data", (d) => chunks.push(d));
  const done = new Promise<Buffer>((resolve, reject) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);  
  });
  const customer =
    params.customer ||
    {
      name: params.user?.fullName,
      email: params.user?.email,
      phone: params.user?.phone
        ? `${params.user?.countryCode || ""}${params.user?.phone || ""}`.trim()
        : "-",
    };
  const pageWidth = doc.page.width;
  const left = doc.page.margins.left; // 40
  const right = pageWidth - doc.page.margins.right;

  // =========================
  // Colors / Styles (modern)
  // =========================
  const C = {
    ink: "#0f172a",
    sub: "#475569",
    muted: "#64748b",
    line: "#e2e8f0",
    card: "#f8fafc",
    accent: "#2563eb",
    headerRow: "#eef2ff",
  };

  // =========================
  // Helpers
  // =========================
  function roundedRect(x: number, y: number, w: number, h: number, r = 10) {
    return doc.roundedRect(x, y, w, h, r); // ✅ return for chaining
  }

  function pill(x: number, y: number, text: string, bg: string, fg: string) {
    const padX = 8;
    const h = 16;

    doc.save();
    doc.font("Helvetica-Bold").fontSize(9);
    const w = doc.widthOfString(text) + padX * 2;

    doc.fillColor(bg);
    roundedRect(x, y, w, h, 8).fill();

    doc.fillColor(fg);
    doc.text(text, x + padX, y + 4, { lineBreak: false });

    doc.restore();
    return { w, h };
  }

  function drawTableHeader(tableX: number, tableY: number, tableW: number) {
    // header row background
    doc.save();
    doc.fillColor(C.headerRow);
    roundedRect(tableX, tableY, tableW, 28, 12).fill();
    doc.restore();

    // header labels
    const colProduct = tableX + 14;
    const colPrice = tableX + 330;
    const colQty = tableX + 420;
    const colTotal = tableX + 470;

    doc.font("Helvetica-Bold").fontSize(9).fillColor(C.ink);
    doc.text("Product", colProduct, tableY + 9);
    doc.text("Price", colPrice, tableY + 9);
    doc.text("Qty", colQty, tableY + 9);
    doc.text("Total", colTotal, tableY + 9);

    return { colProduct, colPrice, colQty, colTotal, nextY: tableY + 34 };
  }

  // =========================
  // Header (modern card + accent bar)
  // =========================
  const headerY = 28;
  const headerH = 86;

  doc.save();
  doc.fillColor(C.card);
  roundedRect(left, headerY, right - left, headerH, 14).fill();
  doc.fillColor(C.accent);
  roundedRect(left, headerY, 6, headerH, 14).fill();
  doc.restore();

  // logo
  if (logoPath) {
    try {
      if (fs.existsSync(logoPath)) {
        doc.image(logoPath, left + 16, headerY + 18, { width: 44 });
      }
    } catch {
      // ignore logo errors
    }
  }

  // company name/address
  const companyX = left + 70;
  doc
    .fillColor(C.ink)
    .font("Helvetica-Bold")
    .fontSize(14)
    .text(company.name, companyX, headerY + 18, { align: "left" })
    .font("Helvetica")
    .fontSize(9)
    .fillColor(C.sub)
    .text(company.address, companyX, headerY + 38, {
      align: "left",
      width: 260,
    });

  // invoice label on right
  doc
    .fillColor(C.ink)
    .font("Helvetica-Bold")
    .fontSize(22)
    .text("INVOICE", left, headerY + 18, { align: "right" })
    .font("Helvetica")
    .fontSize(9)
    .fillColor(C.muted)
    .text("Generated by system", left, headerY + 44, { align: "right" });

  // =========================
  // Invoice meta (two-column cards)
  // =========================
  const invoiceNo = `INV-${String(order._id).slice(-8).toUpperCase()}`;
  const created = fmtDate(order?.createdAt);
  const paidAt = fmtDate(order?.paidAt);

  const gateway = String(order.paymentGateway || order.paymentMethod || "COD").toUpperCase();
  const payStatus = String(order.paymentStatus || "unpaid").toUpperCase();

  const metaTop = headerY + headerH + 14;
  const gap = 12;
  const cardW = (right - left - gap) / 2;
  const cardH = 92;

  // Left card: invoice info
  doc.save();
  doc.fillColor(C.card);
  roundedRect(left, metaTop, cardW, cardH, 14).fill();
  doc.restore();

  doc
    .fillColor(C.ink)
    .font("Helvetica-Bold")
    .fontSize(11)
    .text("Invoice Details", left + 14, metaTop + 12);

  doc.font("Helvetica").fontSize(9).fillColor(C.sub);
  const metaLX = left + 14;
  let metaLY = metaTop + 32;
  const metaLine = 14;

  doc.text(`Invoice No: ${invoiceNo}`, metaLX, metaLY);
  metaLY += metaLine;
  doc.text(`Order ID: ${safeText(order._id)}`, metaLX, metaLY);
  metaLY += metaLine;
  doc.text(`Order Date: ${created}`, metaLX, metaLY);

  // Right card: payment info
  const metaRX = left + cardW + gap;

  doc.save();
  doc.fillColor(C.card);
  roundedRect(metaRX, metaTop, cardW, cardH, 14).fill();
  doc.restore();

  doc
    .fillColor(C.ink)
    .font("Helvetica-Bold")
    .fontSize(11)
    .text("Payment", metaRX + 14, metaTop + 12);

  const pillY = metaTop + 30;
  const isPaid = payStatus === "PAID";
  const statusBg = isPaid ? "#dcfce7" : "#fee2e2";
  const statusFg = isPaid ? "#166534" : "#991b1b";

  const p1 = pill(metaRX + 14, pillY, `STATUS: ${payStatus}`, statusBg, statusFg);
  pill(metaRX + 18 + p1.w, pillY, `GATEWAY: ${gateway}`, "#e0e7ff", "#1e40af");

  doc.font("Helvetica").fontSize(9).fillColor(C.sub);
  doc.text(`Paid At: ${paidAt}`, metaRX + 14, metaTop + 56);

  // =========================
  // Customer + Delivery (two cards)
  // =========================
  const blockTop = metaTop + cardH + 12;
  const blockH = 118;

  // Customer card
  doc.save();
  doc.fillColor(C.card);
  roundedRect(left, blockTop, cardW, blockH, 14).fill();
  doc.restore();

  doc
    .fillColor(C.ink)
    .font("Helvetica-Bold")
    .fontSize(11)
    .text("Customer", left + 14, blockTop + 12);

  doc.font("Helvetica").fontSize(9).fillColor(C.sub);

  const phone = user?.phone
    ? `${user?.countryCode || ""}${user?.phone || ""}`.trim()
    : "-";

  let cy = blockTop + 34;
doc.text(`Name: ${safeText(customer?.name)}`, left + 14, cy);
cy += 14;
doc.text(`Email: ${safeText(customer?.email)}`, left + 14, cy);
cy += 14;
doc.text(`Phone: ${safeText(customer?.phone)}`, left + 14, cy);

  // Delivery card
  doc.save();
  doc.fillColor(C.card);
  roundedRect(metaRX, blockTop, cardW, blockH, 14).fill();
  doc.restore();

  doc
    .fillColor(C.ink)
    .font("Helvetica-Bold")
    .fontSize(11)
    .text("Delivery Address", metaRX + 14, blockTop + 12);

  doc.font("Helvetica").fontSize(9).fillColor(C.sub);
  doc.text(safeText(order.address), metaRX + 14, blockTop + 34, {
    width: cardW - 28,
    height: blockH - 42,
  });

  // =========================
  // Items table (modern header row + zebra)
  // =========================
  const tableTop = blockTop + blockH + 14;

  doc
    .fillColor(C.ink)
    .font("Helvetica-Bold")
    .fontSize(12)
    .text("Items", left, tableTop);

  const tableX = left;
  const tableW = right - left;

  let y = tableTop + 14;
  let cols = drawTableHeader(tableX, y, tableW);
  y = cols.nextY;

  doc.font("Helvetica").fontSize(9).fillColor(C.ink);

  const items = order.items || [];
  const rowH = 22;

  for (let i = 0; i < items.length; i++) {
    const it = items[i];
    const priceRs = Number(it.priceSnapshot || 0);
    const qty = Number(it.qty || 0);
    const lineTotal = priceRs * qty;

    // new page safety (keep some space for totals/footer)
    if (y > 700) {
      doc.addPage();

      doc
        .fillColor(C.ink)
        .font("Helvetica-Bold")
        .fontSize(12)
        .text("Items (cont.)", left, 50);

      y = 70;
      cols = drawTableHeader(tableX, y, tableW);
      y = cols.nextY;

      doc.font("Helvetica").fontSize(9).fillColor(C.ink);
    }

    // zebra background
    doc.save();
    doc.fillColor(i % 2 === 0 ? "#ffffff" : "#f8fafc");
    roundedRect(tableX, y - 4, tableW, rowH + 8, 10).fill();
    doc.restore();

    // row text
    doc.fillColor(C.ink);
    doc.text(safeText(it.name), cols.colProduct, y, { width: 300 });
    doc.text(money(priceRs), cols.colPrice, y, { width: 80, align: "left" });
    doc.text(String(qty), cols.colQty, y, { width: 40, align: "left" });
    doc.text(money(lineTotal), cols.colTotal, y, { width: 90, align: "left" });

    y += rowH;
  }

  // =========================
  // Totals (right-side summary card)
  // =========================
  const subtotal = Number(order.subtotal || 0);
  const shipping = Number(order.shippingFee || 0);
  const total = Number(order.total || subtotal + shipping);

  if (y > 660) {
    doc.addPage();
    y = 60;
  }

  const totalsW = 240;
  const totalsX = right - totalsW;
  const totalsY = y + 18;
  const totalsH = 92;

  doc.save();
  doc.fillColor(C.card);
  roundedRect(totalsX, totalsY, totalsW, totalsH, 14).fill();
  doc.restore();

  doc
    .fillColor(C.ink)
    .font("Helvetica-Bold")
    .fontSize(11)
    .text("Summary", totalsX + 14, totalsY + 12);

  doc.font("Helvetica").fontSize(10).fillColor(C.sub);

  doc.text("Subtotal", totalsX + 14, totalsY + 34);
  doc.text(money(subtotal), totalsX + 14, totalsY + 34, {
    align: "right",
    width: totalsW - 28,
  });

  doc.text("Shipping", totalsX + 14, totalsY + 52);
  doc.text(money(shipping), totalsX + 14, totalsY + 52, {
    align: "right",
    width: totalsW - 28,
  });

  doc.font("Helvetica-Bold").fontSize(12).fillColor(C.ink);
  doc.text("Total", totalsX + 14, totalsY + 72);
  doc.text(money(total), totalsX + 14, totalsY + 72, {
    align: "right",
    width: totalsW - 28,
  });

  // =========================
  // Footer
  // =========================
  const footerY = doc.page.height - doc.page.margins.bottom - 30;
  doc.moveTo(left, footerY - 10).lineTo(right, footerY - 10).strokeColor(C.line).stroke();

  doc
    .fillColor(C.muted)
    .font("Helvetica")
    .fontSize(9)
    .text(`Thank you for shopping with ${company.name}.`, left, footerY, {
      align: "center",
    });

  doc.end();
  return done;
}
